// Generates src/js/site.content.js from content/site.config.json at build/dev time.
// The public bundle gets a snapshot of the content with secrets stripped, so pages
// render instantly without waiting for the /api/config request.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(root, "content/site.config.json");
const target = resolve(root, "src/js/site.content.js");

const raw = JSON.parse(readFileSync(source, "utf8"));
const content = publicContent(raw);

mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `// Generated by scripts/build-content.mjs from content/site.config.json. Do not edit.\nexport default ${JSON.stringify(content)};\n`
);
console.log(`[content] ${content.projects.length} projects -> src/js/site.content.js`);

export function publicContent(config) {
  const clean = structuredClone(config);
  delete clean.admin;
  delete clean.nav;
  if (clean.contact) delete clean.contact.telegram;
  return clean;
}
